server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: dev
    password: dev!234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 96680639251-2gmjgisqb6fflk8ml3qn6jlpkq2floru.apps.googleusercontent.com
            client_secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 516564856470398
            client_secret: cce6e220242063aef092ed8c6bb682ab
            scope:
            - email
            - public_profile

          naver:
            client-id: V8eGtp1VRy4cvwo894Ql
            client-secret: h5b555PhAS
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
